use std::collections::HashMap;
use std::fs;
use std::path::Path;
use colored::*;
use anyhow::{anyhow, Context, Result};
use mlua::{Lua, LuaSerdeExt};
use crate::config::{Permission, UserLists};

fn load_raw(path: &str) -> Result<HashMap<String, Vec<String>>> {
    if !Path::new(path).exists() {
        return Ok(HashMap::new());
    }
    let src = fs::read_to_string(path)
        .with_context(|| format!("failed to read user-lists file at {}", path))?;
    let lua = Lua::new();
    let value = lua
        .load(&src)
        .set_name(path)
        .eval::<mlua::Value>()
        .map_err(|e| anyhow!("failed to evaluate lua user-lists at {}: {}", path, e))?;
    let raw: HashMap<String, Vec<String>> = lua
        .from_value(value)
        .map_err(|e| anyhow!("user-lists at {} does not match expected schema: {}", path, e))?;
    Ok(raw)
}

fn lua_string_literal(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{}\"", escaped)
}

// A bare Lua-safe identifier can be written as `name = {...}`. Anything
// else (spaces, leading digit, etc) needs `["name"] = {...}` instead.
fn lua_table_key(s: &str) -> String {
    let is_ident = !s.is_empty()
        && s.chars()
            .next()
            .map(|c| c.is_ascii_alphabetic() || c == '_')
            .unwrap_or(false)
        && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '_');
    if is_ident {
        s.to_string()
    } else {
        format!("[{}]", lua_string_literal(s))
    }
}

fn save_raw(path: &str, entries: &HashMap<String, Vec<String>>) -> Result<()> {
    let mut usernames: Vec<&String> = entries.keys().collect();
    usernames.sort();
    let mut out = String::new();
    out.push_str("-- ---------------------------------------------------------\n");
    out.push_str("-- ::: [ LISKA SUPERUSER PERMITTED-USERS CONFIGURATION ] :::\n");
    out.push_str("-- ---------------------------------------------------------\n");
    out.push_str("--\n");
    out.push_str("-- This file configures users permissions for lksu automatically.\n");
    out.push_str("--\n");
    out.push_str("-- > lksu fails closed: any user not listed here may not run anything\n");
    out.push_str("--                      throught lksu. \"ALL\" grants every command,\n");
    out.push_str("--                      otherwise list the exact absolute paths a\n");
    out.push_str("--                      user may run.\n");
    out.push_str("-- > WARNING: DO NOT EDIT THIS FILE manually! The configuration will\n");
    out.push_str("--            be rewriten by the lksu \"add-user\", \"edit-user\",\n");
    out.push_str("--            and \"remove-user\" commands!\n");
    out.push_str("-- --------------------------------------------------------------------------\n");
    out.push_str("\n");
    out.push_str("return {\n");
    for username in usernames {
        let commands = &entries[username];
        let items: Vec<String> = commands.iter().map(|c| lua_string_literal(c)).collect();
        out.push_str(&format!(
            "    {} = {{ {} }},\n",
            lua_table_key(username),
            items.join(", ")
        ));
    }
    out.push_str("}\n");
    fs::write(path, out).with_context(|| format!("failed to write {}", path))
}

// Add "username" to the permitted list with "commands" or "["ALL"]".
// Fails if the user is already listed, use "edit_user" for that.
pub fn add_user(path: &str, username: &str, commands: &[String]) -> Result<()> {
    validate(username, commands)?;
    let mut entries = load_raw(path)?;
    if entries.contains_key(username) {
        return Err(anyhow!(
            "{} is already in the permitted list! Use --edit-user instead",
            username
        ));
    }
    entries.insert(username.to_string(), commands.to_vec());
    save_raw(path, &entries)?;
    crate::ui::success(&format!("{} is added to the permitted list!", username));
    Ok(())
}

// Replace the command list for an already-permitted "username".
pub fn edit_user(path: &str, username: &str, commands: &[String]) -> Result<()> {
    validate(username, commands)?;
    let mut entries = load_raw(path)?;
    if !entries.contains_key(username) {
        return Err(anyhow!(
            "{} is not in the permitted list! Use --add-user instead",
            username
        ));
    }
    entries.insert(username.to_string(), commands.to_vec());
    save_raw(path, &entries)?;
    crate::ui::success(&format!("Permissions for {} has been updated!", username));
    Ok(())
}

// Remove "username" from the permitted list entirely.
pub fn remove_user(path: &str, username: &str) -> Result<()> {
    let mut entries = load_raw(path)?;
    if entries.remove(username).is_none() {
        return Err(anyhow!("{} is not in the permitted list", username));
    }
    save_raw(path, &entries)?;
    crate::ui::success(&format!(
        "{} has been removed from the permitted list!",
        username
    ));
    Ok(())
}

fn validate(username: &str, commands: &[String]) -> Result<()> {
    if username.trim().is_empty() {
        return Err(anyhow!("username cannot be empty"));
    }
    if commands.is_empty() {
        return Err(anyhow!("provide at least one command or \"ALL\""));
    }
    Ok(())
}

// Print what "user" is permitted to run through lksu (`--command-list`).
pub fn print_permitted_commands(user: &str, lists: &UserLists) {
    match lists.permissions_for(user) {
        Some(Permission::All) => {
            crate::ui::info(&format!("{} is permitted to run: {}.", user, "ALL commands".bright_green()))
        }
        Some(Permission::Commands(cmds)) => {
            crate::ui::info(&format!("{} is permitted to run:", user));
            for c in cmds {
                println!("  {} {}", ">".bright_green(), c.bright_green());
            }
        }
        None => crate::ui::info(&format!("{} is not permitted to run any commands.", user)),
    }
}

// One row of "--user-list" output.
pub struct SystemAccount {
    pub username: String,
    pub uid: u32,
}

// List real accounts from "/etc/passwd": root plus anything at or
// above "min_uid" (1000 on most distros, matching /etc/login.defs
// UID_MIN), so system/service accounts don't clutter the output.
pub fn list_system_accounts(min_uid: u32) -> Result<Vec<SystemAccount>> {
    let contents = fs::read_to_string("/etc/passwd").context("failed to read /etc/passwd")?;
    let mut accounts = Vec::new();
    for line in contents.lines() {
        let fields: Vec<&str> = line.split(':').collect();
        if fields.len() < 3 {
            continue;
        }
        let username = fields[0];
        let Ok(uid) = fields[2].parse::<u32>() else {
            continue;
        };
        if uid == 0 || uid >= min_uid {
            accounts.push(SystemAccount {
                username: username.to_string(),
                uid,
            });
        }
    }
    accounts.sort_by_key(|a| a.uid);
    Ok(accounts)
}

// Print "--user-list" output.
pub fn print_system_accounts(accounts: &[SystemAccount]) {
    if accounts.is_empty() {
        crate::ui::warning("No accounts found!");
        return;
    }
    crate::ui::info("All accounts on this system:");
    for account in accounts {
        let uid_ui = format!("UID: {}", account.uid);
        println!("  > {} [ {} ]", account.username.bright_green(), uid_ui.bright_green());
    }
}
